### ISSUE TITLE
Broken Makefile

### ISSUE THREAD

**Issue by mark-i-m** [krzysz00/rust-kernel#1]
In the root Makefile, should

```
RUSTSRC = deps/rust/
```

be changed to 

```
RUSTSRC = rust
```

or am I missing something?

**Comment by krzysz00** [comment]
`RUSTSRC` is the directory containing a copy of the Rust sources (since the Makefile in `deps` needs to compile `libcore` and friends). You can either symlink those sources to `deps/rust/` or call `make` with a different value of `RUSTSRC`

Does that help?

**Comment by mark-i-m** [comment]
Thanks, I forgot that more than one Makefile needs to access the `RUSTSRC` variable. In the `deps` directory, this build system breaks (because it is looking for `deps/deps/rust/`), so I think you need to override the value in that particular Makefile, right?

**Comment by mark-i-m** [comment]
Also, do you have a particular suggestion for a commit of the rust repo?

**Comment by krzysz00** [comment]
I see what your original suggestion was, and I'm going to fix that.

Current maser is good until  1.1 beta comes out. (Since beta is just a snapshot of master at a particular point).

**Comment by krzysz00** [comment]
Also, what do you think about the kernel in general?

**Comment by mark-i-m** [comment]
I haven't gotten to look much at the code, but it's impressive that you've made this much progress in a short time. I'm still trying to get the minimal amount of libraries need to compile. I am going to try compiling with just libcore, but I'm not sure if it will work.

**Comment by krzysz00** [comment]
You need a "normal" copy of Rust (just grab the binaries with `rustup.sh --channel=nightly` or `multirust`). Then you use that to cross-compile the libraries from source.

**Comment by mark-i-m** [comment]
I did install the nightly rust (with `$ yaourt -S rust-nightly`), and that seems to be working fine. However when I try to compile I get the following errors:

```
$ make
make -C deps all
make[1]: Entering directory '/home/me/Downloads/rust-kernel/deps'
rustc --target=../i686-unknown-elf.json -L . --crate-type=rlib -C opt-level=3 -Z no-landing-pads rust/src/libcore/lib.rs
rust/src/libcore/intrinsics.rs:197:9: 197:51 error: unrecognized intrinsic function: `size_of_val` [E0093]
rust/src/libcore/intrinsics.rs:197     pub fn size_of_val<T: ?Sized>(_: &T) -> usize;
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/intrinsics.rs:199:9: 199:56 error: unrecognized intrinsic function: `min_align_of_val` [E0093]
rust/src/libcore/intrinsics.rs:199     pub fn min_align_of_val<T: ?Sized>(_: &T) -> usize;
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust/src/libcore/intrinsics.rs:201:9: 201:48 error: unrecognized intrinsic function: `drop_in_place` [E0093]
rust/src/libcore/intrinsics.rs:201     pub fn drop_in_place<T: ?Sized>(_: *mut T);
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Makefile:13: recipe for target 'libcore.rlib' failed
make[1]: *** [libcore.rlib] Error 101
make[1]: Leaving directory '/home/me/Downloads/rust-kernel/deps'
Makefile:9: recipe for target 'deps' failed
make: *** [deps] Error 2
```

**Comment by mark-i-m** [comment]
I think I figured it out. I just had to checkout an earlier version of rust.

**Comment by krzysz00** [comment]
You installed [this one](https://aur.archlinux.org/packages/rust-nightly-bin/), right?  

Yeah, you need the version of the sources reported by `rustc --version`

Should document that.

**Comment by mark-i-m** [comment]
Ah, I see. That's what I was missing. Thanks!

**Comment by krzysz00** [comment]
README's been updated. Thanks for poking me into doing that.

**Comment by mark-i-m** [comment]
Thanks for your help
